Update export_mail_to_drop

diff --git a/libexec/export_mail_to_drop b/libexec/export_mail_to_drop
--- a/libexec/export_mail_to_drop
+++ b/libexec/export_mail_to_drop
@@ -33,8 +33,8 @@ fi
 #-----------------------------------------------------------------------------
 # DISK SPACE CHECK
 #-----------------------------------------------------------------------------
-if [ "$(df -P /home | awk 'NR==2 {print $5+0}')" -gt 92 ]; then
-    echo "[ERROR] /home usage > 92%. Aborting." >&2
+if [ "$(df -P /home | awk 'NR==2 {print $5+0}')" -gt 90 ]; then
+    echo "[ERROR] /home usage > 90%. Aborting." >&2
     exit 1
 fi
 
